spring:
  datasource:
    url: jdbc:mysql://interview-db.c9f81hbjgade.ap-south-1.rds.amazonaws.com:3306/interview_db
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: Aiswaryakuday
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
server:
  port: 8080